name: Update Coder Template

on:
  release:
    types: [ released, prereleased ]

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Get latest commit hash
        id: latest_commit
        run: echo "hash=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
      - name: Get commit title
          id: commit_title
          run: echo "title=$(git log -1 --pretty=%s)" >> $GITHUB_OUTPUT

      - name: Update Coder Template
          uses: matifali/update-coder-template@v3
          with:
            id: coder-php-laravel
            dir: coder-php-laravel
            url: ${{ secrets.CODER_URL }}
            name: ${{ steps.latest_commit.outputs.hash }}
            message: ${{ steps.commit_title.outputs.title }}
            coder_session_token: ${{ secrets.CODER_SESSION_TOKEN }}
